baseURL: "https://manut.dev"
title: "manut.dev"
theme: ["paperMod"]
uglyURLs: true
enableRobotsTXT: true
minify:
  disableJSON: true
mainsections: ["posts", "papermod"]

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives.html
          weight: 5
        - name: Search
          url: search.html
          weight: 10
        - name: Tags
          url: tags.html
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  TocOpen: true
