AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sam template for manut.dev

Resources:
  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: ResponseHeadersPolicy
        CustomHeadersConfig:
          Items:
            - Header: "Cross-Origin-Opener-Policy"
              Value: "same-origin"
              Override: true
            - Header: "Cross-Origin-Embedder-Policy"
              Value: "require-corp"
              Override: true

  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - "manut.dev"
          - "*.manut.dev"
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:668933070809:certificate/4992578c-fa73-47cf-8424-3bf7481517d6
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - DomainName: !GetAtt StaticWebsiteBucket.WebsiteURL
            Id: !Sub "${AWS::StackName}-S3-manut-origin"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: !Sub "${AWS::StackName}-S3-manut-origin"
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          MaxTTL: 3600
          DefaultTTL: 3600
          MinTTL: 0
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html

  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-static-website-bucket"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Id: PublicReadGetObject
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${AWS::StackName}-static-website-bucket/*"

Outputs:
  WebsiteCloudFrontDistribution:
    Description: "CloudFront distribution URL"
    Value: !GetAtt WebsiteCloudFrontDistribution.DomainName
  S3WebsiteEndpoint:
    Description: "S3 bucket URL"
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
