name: Build and deploy backend

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ROLE_TO_ASSUME: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/Manut-GithubAction-Role

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Sam CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build
        run: sam build

      - name: Deploy
        run: sam deploy --no-fail-on-empty-changeset
